### ISSUE TITLE
TypeError: Object input.css has no method 'includes'

### ISSUE THREAD

**Issue by TimBuckley** [sabeurthabti/react-native-css#13]
Not sure why this is failing. Apparently `input` is not defined as a file.

```
tbuck:Desktop $ react-native-css input.css output.js
React-native-css - v1.2.2

/usr/local/lib/node_modules/react-native-css/build/index.js:28
		if (input.includes('scss')) {
		          ^
TypeError: Object /Users/tbuckley/Desktop/input.css has no method 'includes'
    at Object.parse (/usr/local/lib/node_modules/react-native-css/build/index.js:28:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-css/bin/react-native-css:20:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by sabeurthabti** [comment]
@TimBuckley I have taken out support for sass. I will be updating the library soon to include sass again. Can you use css files for now? I will be doing a release later this evening.

**Comment by sabeurthabti** [comment]
@TimBuckley Thank you, I will be adding a fix now.

**Comment by TimBuckley** [comment]
Thanks @sabeurthabti!

**Comment by sabeurthabti** [comment]
@TimBuckley 

Hi. Can you test the new version for me, I added sass support too. 

uninstall current verison
``` shell
npm uninstall react-native-css -g
```

``` shell
npm install react-native-css@1.2.4 -g
```
And I made changes to the CLI, you have to pass in the flags (-i and -o). 

``` shell 
react-native-css -i input.css -o output.js
```

**Comment by TimBuckley** [comment]
Looks like a typo of `build/index.js` as `buidl/index.js`  in `bin/react-native-css`.

```
tbuck:css-test $ react-native-css -i input.css -o output.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../buidl/index.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-css/bin/react-native-css:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by sabeurthabti** [comment]
@TimBuckley yeah - https://circleci.com/gh/sabeurthabti/react-native-css/30

**Comment by sabeurthabti** [comment]
tested react-native-css@1.2.9

**Comment by sabeurthabti** [comment]
@TimBuckley tested tested react-native-css@1.2.11 - all bugs should be fixed.

**Comment by TimBuckley** [comment]
Looks like those problems are solved. Thanks!

**Comment by sabeurthabti** [comment]
@TimBuckley  thanks for taking time to test those :dart:
