### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by Lxxyx** [sabeurthabti/react-native-css#24]
when I want to use react-native-css like this
```
react-native-css ./styles/css/new.css ./styles/js/style.js
```
then
```
/Users/lxxyx/.nvm/versions/node/v5.8.0/lib/node_modules/.react-native-css_npminstall/react-native-css/1.2.29/react-native-css/build/index.js:58
          cb(styleSheet);
          ^

TypeError: cb is not a function
    at /Users/lxxyx/.nvm/versions/node/v5.8.0/lib/node_modules/.react-native-css_npminstall/react-native-css/1.2.29/react-native-css/build/index.js:58:11
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
I had try **sass scss and css**
but i got same question.

My OS is mac osx 10.10 and node.js 5.7/5.8(5.7,5.8,4.4LTS got same question)

Thank you

**Comment by sabeurthabti** [comment]
@Lxxyx I will look into this

**Comment by sabeurthabti** [comment]
@Lxxyx this was an oversight from myself, I have pushed a fix. I will add tests that will cover this scenario so that it wont happen in the future.

**Comment by sabeurthabti** [comment]
@Lxxyx  react-native-css@1.2.31

**Comment by Lxxyx** [comment]
@sabeurthabti Ok,Thank you~
